### PR TITLE
Fix logical type errors

### LINKED ISSUE #722: SQLite adapter fails to raise error
When I configured Backend to use SQLite and did this:

```
$ zmb start_domain_test --domain example.com | jq .
{
  "jsonrpc": "2.0",
  "result": null,
  "id": 1
}
```

We should never be getting `"result": null` here. Something is wrong.

```
$ tail -n4 /home/mattiasp/.log/zonemaster/zm-rpcapi.log
DBD::SQLite::db selectrow_array failed: no such table: test_results at /home/mattiasp/zonemaster-backend/lib/Zonemaster/Backend/DB/SQLite.pm line 190.
DBD::SQLite::db do failed: no such table: test_results at /home/mattiasp/zonemaster-backend/lib/Zonemaster/Backend/DB/SQLite.pm line 223.
DBD::SQLite::db selectrow_array failed: no such table: test_results at /home/mattiasp/zonemaster-backend/lib/Zonemaster/Backend/DB/SQLite.pm line 226.
Use of uninitialized value $id in numeric gt (>) at /home/mattiasp/zonemaster-backend/lib/Zonemaster/Backend/DB/SQLite.pm line 228.
```

So I forgot to initialize my database. That's obviously wrong. But it should result in an error response. We're getting a successful response with `"result": null`. Also we're making three failed database queries. We should be aborting after the first failure.

### LINKED ISSUE #724: Broken domain name validation
Domain name validation was broken in release 6.0.1.

In version 5.0.2 I get:
```
$ zmb start_domain_test --domain in/va/lid.se
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32603,
    "message": "The domain name contains unauthorized character(s) \n"
  }
}
```

In version 6.0.1 I get:
```
$ zmb start_domain_test --domain in/va/lid.se
{
  "id": 1,
  "result": "8943ee6faf1f9af6",
  "jsonrpc": "2.0"
}
```

Note that MySQL and PostgreSQL were the only supported databases back in version 5.0.2.

### PR DESCRIPTION
**Pull request by mattias-p**
This re-enables the domain name validation we had back in 5.0.2.

With these changes the error response for invalid domain names caught by _check_domain is "Internal server error". This is less than great, but at least it's much better than accepting invalid strings.

Fixes #724.

### CODE REVIEW

**Review by matsduf — APPROVED** [review]

**Comment by mattias-p** [comment]
I'd forgotten to take one of the branches in _check_domain into account, so I added a commit to fix that.

In order to isolate the error more easily I updated some of the tests in the failing test file to more clearly isolate tests from each other, to more clearly isolate execution phases from verification phases, to give slightly more feedback, and to not modify the global $frontend_params variable.

**Review by matsduf — APPROVED** [review]

File: lib/Zonemaster/Backend/RPCAPI.pm [hunk 1]
```diff
@@ -193,7 +193,7 @@ sub get_data_from_parent_zone {
 sub _check_domain {
     my ( $self, $dn, $type ) = @_;
 
-    my $result = eval {
+    ( $dn, my $result ) = eval {
```
Comment (pnax) [inline lib/Zonemaster/Backend/RPCAPI.pm:196]: Just wondering if this variable name `dn` has a meaning ? I know this is not a new name added in this PR, I was just wondering if someone knew what `dn` stands for. And if this is not explicit enough, why not update the name to something more obvious.

**Review by pnax — COMMENTED** [review]
I like the refactoring of the `test_validate_syntax.t` file. Just 2 questions on the code. Beside those this looks good to me.

File: lib/Zonemaster/Backend/RPCAPI.pm (hunk 1 above)
Comment (mattias-p) [reply lib/Zonemaster/Backend/RPCAPI.pm:196]: To me it's clearly an abbreviation of "domain name". But I agree that it's not great. I'll change it.

**Comment by mattias-p** [comment]
When I had another look at this I realized the eval/handle_exception construct in _check_domain is useless. It only makes sense to have eval/handle_exception in top-level procedures. So I threw it out from _check_domain.

Initially I was going to get rid of all instances of `$dn`. But then `get_data_from_parent_zone` is doing weird things and for this PR I don't feel like digging into it, so I'm leaving it as is.

File: lib/Zonemaster/Backend/RPCAPI.pm (hunk 1 above)
Comment (matsduf) [reply lib/Zonemaster/Backend/RPCAPI.pm]: I think it would help to be consistent on what variable name to use when referring to zone name -- or domain name, if you wish -- to be tested. And to use that variable every time it works, and to reserve it for that.

File: lib/Zonemaster/Backend/RPCAPI.pm [hunk 2]
```diff
@@ -191,65 +191,55 @@ sub get_data_from_parent_zone {
...
+            if ( $@ ) {
                 return (
-                    $dn,
+                    $domain,
                     {
-                        status => 'nok',
-                        message =>
-                        encode_entities( "$type contains non-ascii characters and IDNA is not installed" )
+                        status  => 'nok',
+                        message => encode_entities( "The domain name is not a valid IDNA string and cannot be converted to an A-label" )
```
Comment (matsduf) [inline lib/Zonemaster/Backend/RPCAPI.pm:208]: To be correct, a domain name is not an A-label. An A-label is a label within a domain name.

"The domain name has one or more non-ASCII label that cannot be converted to an A-label"

**Comment by mattias-p** [comment]
@pnax, @matsduf Please review again.

File: lib/Zonemaster/Backend/RPCAPI.pm [hunk 3]
```diff
@@ -191,65 +191,55 @@ sub get_data_from_parent_zone {
 
 
 sub _check_domain {
-    my ( $self, $dn, $type ) = @_;
+    my ( $self, $domain, $type ) = @_;
```
Comment (matsduf) [inline lib/Zonemaster/Backend/RPCAPI.pm:194]: I think it would help if the API of this method is defined. Especially spell out what "$type" is for.

File: lib/Zonemaster/Backend/RPCAPI.pm [hunk 4]
```diff
@@ -191,65 +191,55 @@ sub get_data_from_parent_zone {
...
-        if( $dn !~ m/^[\-a-zA-Z0-9\.\_]+$/ ) {
+        else {
             return (
-                $dn,
+                $domain,
                 {
-                status  => 'nok',
-                message => encode_entities( "The domain name character(s) not supported")
+                    status  => 'nok',
+                    message => encode_entities( "$type contains non-ascii characters and IDNA is not installed" )
```
Comment (matsduf) [inline lib/Zonemaster/Backend/RPCAPI.pm:218]: "$type contains non-ascii label but support for conversion from U-label to A-label is not installed"

File: lib/Zonemaster/Backend/RPCAPI.pm [hunk 5]
```diff
@@ -191,65 +191,55 @@ sub get_data_from_parent_zone {
...
     }
-    elsif ($result) {
-		return $result;
+
+    if ( $domain !~ m/^[\-a-zA-Z0-9\.\_]+$/ ) {
+        return (
+            $domain,
+            {
+                status  => 'nok',
+                message => encode_entities( "The domain name character(s) not supported" )
```
Comment (matsduf) [inline lib/Zonemaster/Backend/RPCAPI.pm:229]: "The domain name contains one or more characters not supprted"

File: lib/Zonemaster/Backend/RPCAPI.pm [hunk 6]
```diff
@@ -191,65 +191,55 @@ sub get_data_from_parent_zone {
...
     
     my %levels = Zonemaster::Engine::Logger::Entry::levels();
     my @res;
-    @res = Zonemaster::Engine::Test::Basic->basic00($dn);
+    @res = Zonemaster::Engine::Test::Basic->basic00( $domain );
     @res = grep { $_->numeric_level >= $levels{ERROR} } @res;
-    if (@res != 0) {
-        return ( $dn, { status => 'nok', message => encode_entities( "$type name or label is too long" ) } );
+    if ( @res != 0 ) {
+        return ( $domain, { status => 'nok', message => encode_entities( "$type name or label is too long" ) } );
```
Comment (matsduf) [inline lib/Zonemaster/Backend/RPCAPI.pm:239]: "$type name or at least one of its labels is too long"

File: lib/Zonemaster/Backend/RPCAPI.pm [hunk 7]
```diff
@@ -191,65 +191,55 @@ sub get_data_from_parent_zone {
...
     }
 
-    return ( $dn, { status => 'ok', message => 'Syntax ok' } );
+    return ( $domain, { status => 'ok', message => 'Syntax ok' } );
```
Comment (matsduf) [inline lib/Zonemaster/Backend/RPCAPI.pm:242]: "Valid name"

**Review by matsduf — CHANGES_REQUESTED** [review]

**Review by matsduf — APPROVED** [review]
An issue of the incorrect messages has been created in #735.

**Comment by mattias-p** [comment]
## Release testing for v2021.1

I've verified this using the command in #724 on CentOS 7 and CentOS 8.
