### PR TITLE
Fix warning in RPCAPI

### LINKED ISSUE #631: Use of uninitialized value in zm-rpcapi.log
I'm seeing lots of these warnings repeated in zm-rpcapi.log:
```
Use of uninitialized value in concatenation (.) or string at /usr/local/share/perl/5.26.1/Zonemaster/Backend/RPCAPI.pm line 389.
```
The file I'm looking at has 82371 of them distributed across 13 restarts.

For the record this particular installation is running Zonemaster::Backend 5.0.2 on Ubuntu 18.04 and MySQL.

### PR DESCRIPTION
**Pull request by mattias-p**
I think I've got this figured out now.

* `$entry->{string}` never seems to exist, but  `Zonemaster::Engine::Logger::Entry::string` does exist, and it actually makes sense to call that on proper `Z::E::L::Entry` objects.
* Calling bless to get an `Z::E::L::Entry` object doesn't work because the object doesn't get properly initialized we end up crashing. Instead we should just be good citizens and call `Z::E::L::Entry::new`.
* The check of `Z::E::Translator::data` is kind of useless. The `Z::E::T::translate_tag` performs essentially the same check and returns $entry->string if the check fails. It's better to just use the `Z::E::T::translate_tag` return value.
* The early return was unfortunate because that code path failed to reset the locale, so I fixed that as well.

Fixes #631.

### CODE REVIEW

**Comment by matsduf** [comment]
I have no objection to your changes, but I cannot see why they should be in the same PR.

**Comment by mattias-p** [comment]
This fix is broken. I'll come back with an update.

File: lib/Zonemaster/Backend/Translator.pm [hunk 1]
```diff
@@ -45,17 +45,13 @@ sub translate_tag {
...
-    my $octets = Zonemaster::Engine::Translator::translate_tag( $self, $blessed_entry );
+    my $entry = Zonemaster::Engine::Logger::Entry->new( %{ $hashref } );
+    my $octets = Zonemaster::Engine::Translator::translate_tag( $self, $entry );
     $self->locale( $previous_locale );
-    my $str = decode_utf8( $octets );
-    return $str;
+
+    return ( defined $octets )
+      ? decode_utf8( $octets )
+      : $entry->string;
```
Comment (matsduf) [inline lib/Zonemaster/Backend/Translator.pm:54]: The following is Zonemaster::Engine::Translator::translate_tag:

```
sub translate_tag {
    my ( $self, $entry ) = @_;

    return $self->_translate_tag( $entry->module, $entry->tag, $entry->printable_args ) // $entry->string;
}
```

Won't it already return $entry->string if translation (_translate_tag) fails?

Comment (mattias-p) [reply lib/Zonemaster/Backend/Translator.pm:54]: It will. I'll make an update.

**Review by matsduf — APPROVED** [review]
