### PR TITLE
Fix internationalized testing failure with error: "malformed UTF-8 character in JSON string"

### LINKED ISSUE #931: Testing internationalized characters is broken with PostgreSQL
Testing a domain such as `café.fr` breaks the Backend.
https://zonemaster.net/result/bb711a47bf7f203f

The `params` value is stored differently in database, as string in SQLite and MySQL, as a JSON object in PostgreSQL. This has an impact on how each driver retrieves the data from database in `get_test_params`.

## Playing with the drivers

It is possible to inspect the value of `$params_json` returned by each driver with the module [Data::Peek](https://metacpan.org/pod/Data::Peek)

https://github.com/zonemaster/zonemaster-backend/blob/b8df4d0ad702cbe05e0dddea3530f3c7ffd8ba68/lib/Zonemaster/Backend/DB.pm#L256

The following patch is applied to the code, to dive into the `$params_json` string:

```diff
diff --git a/lib/Zonemaster/Backend/DB.pm b/lib/Zonemaster/Backend/DB.pm
index 3898ab8..df4975c 100644
--- a/lib/Zonemaster/Backend/DB.pm
+++ b/lib/Zonemaster/Backend/DB.pm
@@ -14,6 +14,8 @@ use Log::Any qw( $log );
 use Zonemaster::Engine::Profile;
 use Zonemaster::Backend::Errors;
 
+use Data::Peek;
+
 requires qw(
   add_batch_job
   create_db
@@ -258,6 +260,8 @@ sub get_test_params {
     die Zonemaster::Backend::Error::ResourceNotFound->new( message => "Test not found", data => { test_id => $test_id } )
         unless defined $params_json;
 
+    print DPeek( $params_json ) . "\n";
+
     my $result;
     eval {
         # TODO: do we use "encode_utf8" as this was the case in PostgreSQL
```

Then foreach database, testing with the `café.fr` domain will give the outputs listed below

```sh
curl -sH "Content-Type: application/json" --data '{"method":"start_domain_test","params":{"domain":"café.fr"},"id":1,"jsonrpc":"2.0"}' localhost:5000/api
```

| engine | output |
| --- | --- |
| SQLite | `PV("{\"domain\":\"caf\303\251.fr\",\"ds_info\":[],\"ipv4\":true,\"ipv6\":true,\"nameservers\":[],\"priority\":10,\"profile\":\"defa"...\0)`
| MySQL | `PV("{\"domain\":\"caf\303\251.fr\",\"ds_info\":[],\"ipv4\":true,\"ipv6\":true,\"nameservers\":[],\"priority\":10,\"profile\":\"defa"...\0)` |
| PostgreSQL | `PV("{\"domain\":\"caf\303\251.fr\",\"ds_info\":[],\"ipv4\":true,\"ipv6\":true,\"nameservers\":[],\"priority\":10,\"profile\":\"defa"...\0) [UTF8 "{"domain":"caf\x{e9}.fr","ds_info":[],"ipv4":true,"ipv6":true,"nameservers":[],"priority":10,"profile":"default","queue":0}"]` |

The Perl's internal representation of the string is different. The string retrieved with DBD::pg has an UTF-8 section in the DPeek output that is not present with SQLite and MySQL. This requires to be careful when calling [`decode_json`](https://metacpan.org/pod/JSON::PP#decode_json) that _"expects an UTF-8 (binary) string"_

### PR DESCRIPTION
**Pull request by pnax**
## Purpose

The different database drivers do not retrieve the data with the same Perl's internal representation. Therefore it is required to check this representation before calling "decode_json" that "expects an UTF-8 (binary) string" (https://metacpan.org/pod/JSON::PP#decode_json).

## Context

Fixes #931
Also see #570

## Changes

Fix the `get_test_params` method in `DB.pm`.

## How to test this PR

Check that internationalized and non-internationalized domains works properly for all database engines.

### CODE REVIEW

File: lib/Zonemaster/Backend/DB.pm [hunk 1]
```diff
@@ -260,9 +260,11 @@ sub get_test_params {
...
     my $result;
     eval {
-        # TODO: do we use "encode_utf8" as this was the case in PostgreSQL
-        #       (see commit diff)
-        $result = decode_json( $params_json );
+        if ( utf8::is_utf8( $params_json ) ) {
+            $result = decode_json( encode_utf8( $params_json ) );
+        } else {
+            $result = decode_json( $params_json );
+        }
```
Comment (matsduf) [inline lib/Zonemaster/Backend/DB.pm:267]: #571 also handles "$result->{results}". Is it certain that it is not needed to include that? Just to be safe?

Comment (pnax) [reply lib/Zonemaster/Backend/DB.pm:267]: This part of the code has not been modified with the latest release, so I thought to keep it that way for the fix release and update it with v2022.1. However, as said in #934, I'm fine with replacing this PR (#932) with #934 and include it into v2021.2.1.

Comment (matsduf) [reply lib/Zonemaster/Backend/DB.pm:267]: That seems reasonable.

**Comment by matsduf** [comment]
Before I press the approve button I will run a test.

**Review by mattias-p — APPROVED** [review]
LGTM. Thought I haven't tested it.

**Review by matsduf — APPROVED** [review]
I approve.
